package com.maqautocognita.constant;

/**
 * @author sc.chi csc19840914@gmail.com
 */
public enum ScreenObjectType {
    QUESTION, ANSWER_CONTAINER, PICTURE, PHONIC_SOUND_SYMBOL_LEFT, PHONIC_SOUND_SYMBOL_RIGHT, SOUND, LETTER, WORD, MICROPHONE,
    UPPERCASE, LOWERCASE, SPEECH_ICON, KEYBOARD, HINTS, BORDER, MENU_LETTER, MENU_LESSON_DOT, MENU_REVIEW_DOT, MENU_MASTERY_TEST_DOT,
    BUTTON
}
